# Copyright (c) 2022-2026, PostgreSQL Global Development Group

backend_sources += files(
  'dist_commands.c',
  'dist_connection.c',
  'dist_copy.c',
  'dist_executor.c',
  'dist_guc.c',
  'dist_main.c',
  'dist_node.c',
  'dist_shmem.c',
  'dist_transaction.c',
  'failure_detector.c',
  'placement.c',
  'query_router.c',
  'raft.c',
  'raft_log.c',
  'raft_rpc.c',
  'raft_worker.c',
  'rebalancer.c',
  'shard.c',
)
